/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import EstructuraDatos.ArbolB;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author leider
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        areaResultado.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        palabraBuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        limpiar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));

        buscar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        buscar.setForeground(new java.awt.Color(254, 254, 254));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar2.png"))); // NOI18N
        buscar.setText("Buscar");
        buscar.setBorder(null);
        buscar.setBorderPainted(false);
        buscar.setContentAreaFilled(false);
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscar.setIconTextGap(-3);
        buscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar3.png"))); // NOI18N
        buscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar1.png"))); // NOI18N
        buscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        texto.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese su  texto"));
        jScrollPane1.setViewportView(texto);

        limpiar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        limpiar.setForeground(new java.awt.Color(254, 254, 254));
        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clear1.png"))); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.setBorder(null);
        limpiar.setBorderPainted(false);
        limpiar.setContentAreaFilled(false);
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limpiar.setIconTextGap(-3);
        limpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clear3.png"))); // NOI18N
        limpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clear2.png"))); // NOI18N
        limpiar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cerrar.setForeground(new java.awt.Color(254, 254, 254));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/close1.png"))); // NOI18N
        cerrar.setText("Cerrar");
        cerrar.setBorder(null);
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.setIconTextGap(-3);
        cerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/close3.png"))); // NOI18N
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/close2.png"))); // NOI18N
        cerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        areaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado de la Busqueda"));
        jScrollPane2.setViewportView(areaResultado);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Búsqueda de Palabra");

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Ingrese palabra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(palabraBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))))
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 140, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(palabraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
                    /**
                     * Obtenemos los datos de entrada.
                     */
                    String palabras=texto.getText();
                    String aux=texto.getText().replace("\t", " ");
                    aux=aux.trim();
                    String dato=palabraBuscar.getText();
                    int index;
                    int p;
                    int temporal, espacial;
                    
            if(!aux.equals("") || !dato.equals("")) {
                
                   /**
                    * Creamos el arbol binario.
                    */ 
                    ArbolB<String> arbolProblema=new ArbolB<>();
                    /**
                     * Llenamos el arbos binario invocando al metodo llenarArbol.
                     */
                    llenarArbol(arbolProblema,palabras.toLowerCase());
                    /**
                     * Invocamos al metodo del arbol binario denominado busquedaProfundidad,
                     * este mtodo nos dira con un valor boolano si el dato se encuentra en el arbol.
                     */
                    boolean encontrar=arbolProblema.busquedaProfundidad(dato.toLowerCase());
                    /**
                     * Preguntamos al metodo del arbol binario nivelResult en que profundidad encontro el
                     * dato.
                     */
                    index=arbolProblema.nivelResult(dato.toLowerCase());      
                     /**
                     * Preguntamos al metodo del arbol binario profundiad cual es el nivel mas profundo
                     * del arbol.
                     * 
                     */
                    p=arbolProblema.profundidad();
                    /**
                     * Calculando la complejidad temporal.
                     */
                    temporal=(int)Math.pow(2,(p-1));
                    /**
                     * Calculando la complejidad espacial.
                     */
                    espacial=2*(p-1);
                    
                    areaResultado.setText("");
                    areaResultado.append("****Resultado de Busqueda en profundidad****");
                    
                    if(encontrar==true){
                        /**
                         * Si la busqueda salio correcta mostramos lo suiguiente.
                         */
                        
                        areaResultado.append("\nComplejidad Temporal : "+temporal);
                        areaResultado.append("\nComplejidad Espacial : "+espacial);
                        areaResultado.append("\nTipo de arbol : Binario");
                        areaResultado.append("\nNivel Maximo del arbol : "+(p-1));
                        areaResultado.append("\nNivel de la palabra "+palabraBuscar.getText()+" en el arbol : "+index);
                    }else{
                        /**
                         * Si la busqueda fue incorreca mostramos el mensaje.
                         */
                        areaResultado.append("\n la palabra "+dato+" no se encuentra en su texto ingresado");
                        
                    }

                  }else{
                    /**
                     * alertamos los campo a llenar al usuario.
                     */
                        texto.setText("");
                       JOptionPane.showMessageDialog(this, "Debe llenar todas la entradas");
                  }
            
            
            
            // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
            texto.setText("");
            palabraBuscar.setText("");
            areaResultado.setText("");
            texto.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed
    /**
     * Metodo que llena el arbol binario con las palabras insertadas.
     */
    public void llenarArbol(ArbolB<String> arbolProblema, String text){
        String cadena=text.trim();
        System.out.println(cadena);
        llenarArbol(arbolProblema, cadena, 0, 0);
    }
    private void llenarArbol(ArbolB<String> arbolProblema, String text,int indexxIni, int indexxFin){
        int indexIni=indexxIni;
        int indexFin=indexxFin;
        //ArbolB<String> arbolAyuda=arbolProblema;
        String palabra="";
        int longitud=text.length()-1;
        if(indexFin<=longitud){
            if(text.charAt(indexFin)==' ' && text.charAt(indexFin-1)!=' '){
                palabra=text.substring(indexIni, indexFin);
                palabra=palabra.trim();
                palabra=palabra.replace("\t", " ");
                System.out.println(palabra);
                arbolProblema.insertarAmp(palabra);
                indexIni=indexFin+1;
                indexFin+=1;
                llenarArbol(arbolProblema, text, indexIni, indexFin);
            }else{
                indexFin+=1;
                llenarArbol(arbolProblema, text, indexIni, indexFin);
            }
            if(indexFin==longitud){
                palabra=text.substring(indexIni, indexFin+1);
                palabra=palabra.trim();
                arbolProblema.insertarAmp(palabra);
            System.out.println(palabra);
            }
        }
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField palabraBuscar;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
